### PR TITLE
Updated fill Data page

### PR DESCRIPTION
**Pull request by AmanNinave**
For adding new picker basic html and CSS

### CODE REVIEW

**Comment by AmanNinave** [comment]
Implemented adding picker to database feature

**Comment by AmanNinave** [comment]
sending cluster and packing data to backend

**Review by PatelNeelMahesh — COMMENTED** [review]
You can merge pull request.

**Comment by AmanNinave** [comment]
Backend :- fill Data part done
Front End :- fill Data highlighting Active section and updating UI after data send to the backend

**Review by PatelNeelMahesh — APPROVED** [review]

**Pull request merged**
